version: '3.8'

services:
    app:
        image: php:8.2-apache
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ~/.composer:/tmp/composer
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=laravel-rocket-science
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - mysql
        command: >
            bash -c "
            apt-get update -qq &&
            apt-get install -y --no-install-recommends git zip unzip libzip-dev libpng-dev libonig-dev libxml2-dev > /dev/null &&
            docker-php-ext-install pdo pdo_mysql zip mbstring exif pcntl bcmath gd &&
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
            composer install --optimize-autoloader --no-interaction &&
            php artisan key:generate &&
            chmod -R 777 storage bootstrap/cache &&
            apache2-foreground
            "

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel-rocket-science
        volumes:
            - mysql_data:/var/lib/mysql

    node:
        image: node:18
        volumes:
            - .:/app
            - ~/.npm:/tmp/npm
        working_dir: /app
        ports:
            - "5173:5173"
        command: >
            bash -c "
            npm install &&
            npm run dev
            "

volumes:
    mysql_data:
