version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.php
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ~/.composer:/tmp/composer
            - ./apache-config.conf:/etc/apache2/sites-enabled/000-default.conf
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=laravel-rocket-science
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel-rocket-science
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    vite:
        build:
            context: .
            dockerfile: Dockerfile.node
        volumes:
            - .:/var/www/html
            - vite_node_modules:/var/www/html/node_modules
        ports:
            - "5173:5173"
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true

volumes:
    mysql_data:
    vite_node_modules:
